### ISSUE TITLE
BLE - Thread - Border Router

### ISSUE THREAD

**Issue by HpLightcorner** [LairdCP/Pinnacle_100_oob_demo#1]
Hi Laird Team,
Thanks for this excellent getting started point. I am currently evaluating the Pinnacle 100 for a series of projects - and I also took a deep dive into Thread-Protocol and BLE. 

The Thread-Protocol seems to have many advantages like a more homogenous network - the Pinnacle would act as Border Router. For this (quite advanced) demo, you are using BLE and I am curious why you came to this decision and why Thread was not the first choice for a sensor network like that one you are proposing in this repository? 

I am also trying to start a discussion about creating a Thread border router based on the Pinnacle 100 on the Zephyr mailing list, so maybe there is a chance to get some Input also from your side? Zephyr states that it is able to start multiple network interfaces at the same time, but no automatic routing is applied between those networks. Maybe you could add some comments from your side: What is your opinion about using the Pinnacle as a Thread border router? For more industrial applications like mine, there is no need for a User Interface running on the router, I could simply pre-provision the device so that it can connect to thread.

This would, at least as I have understood, allow each sensor to directly connect to the cloud without the interaction of the border router, and updates could be sent from the cloud to each sensor node as each device is transparently interacting in the network.

**Comment by rerickson1** [comment]
The decision to use BLE is due to our ecosystem of sensors that use BLE.
